version: '3.7'

services:

  # Elastic Search

  elasticsearch:
    hostname: elasticsearch
    networks:
      - monitoring
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    image: 'elasticsearch:8.11.1'
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      #- xpack.security.enabled=false
      #- xpack.security.http.ssl.enabled=false

  kibana:
    hostname: kibana
    networks:
      - monitoring
    ports:
      - '5601:5601'
    volumes:
      - 'kibana_data:/usr/share/kibana/data'
      - 'kibana_config:/usr/share/kibana/config'
    image: 'kibana:8.11.1'
    restart: unless-stopped

networks:
  monitoring:

volumes:
  elasticsearch_data:
  kibana_data:
  kibana_config:
