-- MySQL setup script
-- Run this script to set up the database schema and indexes
-- Warning: This file is automatically generated, do not modify it.

CREATE TABLE `dynamic_configuration` (
    `config_key` VARCHAR(255) PRIMARY KEY,
    `config_value` MEDIUMTEXT
);

CREATE TABLE `sessions` (
    `id` VARCHAR(255) PRIMARY KEY,
    `secret` VARCHAR(255),
    `uid` VARCHAR(255),
    `created` BIGINT,
    `expiration` BIGINT,
    `tfa_pending` BOOLEAN,
    `remote` VARCHAR(255),
    `browser` VARCHAR(255),
    `os` VARCHAR(255)
);

CREATE INDEX `ix_sessions_s_1` ON `sessions`(`uid`);

CREATE TABLE `user_profile` (
    `id` VARCHAR(255) PRIMARY KEY,
    `name` VARCHAR(255),
    `bio` TEXT,
    `image` VARCHAR(255),
    `location` VARCHAR(255),
    `website` VARCHAR(255)
);

CREATE TABLE `user_roles` (
    `id` VARCHAR(255) PRIMARY KEY,
    `permissions` TEXT
);

CREATE TABLE `tp_users` (
    `id` VARCHAR(255) PRIMARY KEY,
    `uid` VARCHAR(255),
    `type` VARCHAR(255),
    `tp_email` VARCHAR(255),
    `tp_username` VARCHAR(255),
    `secret` VARCHAR(255)
);

CREATE INDEX `ix_tp_users_s_1` ON `tp_users`(`uid`);

CREATE TABLE `users` (
    `id` VARCHAR(255) PRIMARY KEY,
    `username` VARCHAR(255),
    `username_lower_case` VARCHAR(255),
    `email` VARCHAR(255),
    `email_verified` BOOLEAN,
    `email_verification_code` VARCHAR(255),
    `email_request` VARCHAR(255),
    `password_hash` VARCHAR(255),
    `password_salt` VARCHAR(255),
    `password_reset_code` VARCHAR(255),
    `password_reset_expiration` BIGINT,
    `role` VARCHAR(255),
    `banned` BOOLEAN,
    `tfa` BOOLEAN,
    `tfa_secret` VARCHAR(255),
    `created` BIGINT,
    `locale` VARCHAR(255)
);

CREATE UNIQUE INDEX `ix_users_s_1` ON `users`(`username_lower_case`);
CREATE UNIQUE INDEX `ix_users_s_2` ON `users`(`email`);
CREATE INDEX `ix_users_s_3` ON `users`(`role`);

CREATE TABLE `wallets` (
    `id` VARCHAR(255) PRIMARY KEY,
    `uid` VARCHAR(255),
    `name` VARCHAR(255),
    `address` VARCHAR(255),
    `encrypted_key` TEXT,
    `password_hash` VARCHAR(255),
    `password_salt` VARCHAR(255)
);

CREATE INDEX `ix_wallets_s_1` ON `wallets`(`uid`);
