name: Mobile application CI

on:
  push:
    branches: [ "master", "main", "develop" ]
    paths:
      - mobile-application/**
      - .github/workflows/mobile-app.yml
  pull_request:
    branches: [ "master", "main", "develop" ]
    paths:
      - mobile-application/**
      - .github/workflows/mobile-app.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: ./mobile-application
      run: npm install

    - name: Run tests
      working-directory: ./mobile-application
      run: npm test
